language: go

go:
  - tip

before_install:
  - go get -v ./...
  - go get -v github.com/axw/gocov/gocov
  - go get -v github.com/mattn/goveralls
  - go get -v golang.org/x/tools/cmd/cover

script:
  - goveralls -v -service travis-ci -repotoken $COVERALLS_TOKEN github.com/anupcshan/sqlgen/sqlgen
